spring.application.name=invoicemanagement

server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/authify_app?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password= Frankleen_1996
spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret.key=mysupersecure256bitsecretkeymysupersecure256bit

server.servlet.context-path=/api/v1.0

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a4aae2001@smtp-brevo.com
spring.mail.password=bskvLfIyZ9QdGrR
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
mail.from=frankfrans96@gmail.com
