package com.inm.dto.invoice.request;

import com.inm.enums.InvoiceStatus;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

@Data
public class InvoiceRequest {


    // Auto-generated by backend
    private String invoiceNumber;

    @NotNull(message = "Invoice date is required")
    private LocalDate invoiceDate;

    private LocalDate dueDate;

    private String subject;

    private String customerNotes;

    private String terms;

    private String orderNumber;

    private String referenceNumber;

    // Example: INR, USD, EUR
    private String currency;

    // Automatically fetched by backend
    private BigDecimal exchangeRate;

    @NotNull(message = "Customer is required")
    private Long customerId;

    private Long salesPersonId;

    @Valid
    @NotEmpty(message = "At least one invoice item is required")
    private List<InvoiceItemRequest> items;

    private Long taxMasterId;

    private BigDecimal subTotal;

    private BigDecimal discountAmount;

    private BigDecimal taxAmount;

    private BigDecimal shippingCharges;

    private BigDecimal adjustment;

    private BigDecimal totalAmount;

    private InvoiceStatus invoiceStatus;
}